In [1]:
!pip install pandas numpy scikit-learn matplotlib seaborn nltk gensim torch transformers tqdm --quiet

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.9/27.9 MB 59.6 MB/s eta 0:00:00

In [9]:
!pip install nltk gensim transformers torch scikit-learn wordcloud matplotlib seaborn
!python -m nltk.downloader punkt punkt_tab stopwords

Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (3.9.1)
Requirement already satisfied: gensim in /usr/local/lib/python3.12/dist-packages (4.4.0)
Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (4.57.1)
Requirement already satisfied: torch in /usr/local/lib/python3.12/dist-packages (2.8.0+cu126)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: wordcloud in /usr/local/lib/python3.12/dist-packages (1.9.4)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (3.10.0)
Requirement already satisfied: seaborn in /usr/local/lib/python3.12/dist-packages (0.13.2)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk) (8.3.0)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk) (1.5.2)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk) (2024.11.6)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk) (4.67.1)
Requirement already satisfied: numpy>=1.18.5 in /usr/local/lib/python3.12/dist-packages (from gensim) (2.0.2)
Requirement already satisfied: scipy>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from gensim) (1.16.3)
Requirement already satisfied: smart_open>=1.8.1 in /usr/local/lib/python3.12/dist-packages (from gensim) (7.5.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers) (3.20.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.34.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.36.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from transformers) (2.32.4)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.6.2)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch) (1.13.3)
Requirement already satisfied: networkx in /usr/local/lib/python3.12/dist-packages (from torch) (3.5)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec in /usr/local/lib/python3.12/dist-packages (from torch) (2025.3.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch) (12.6.77)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch) (12.6.77)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.6.80 in /usr/local/lib/python3.12/dist-packages (from torch) (12.6.80)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.6.4.1 in /usr/local/lib/python3.12/dist-packages (from torch) (12.6.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.0.4 in /usr/local/lib/python3.12/dist-packages (from torch) (11.3.0.4)
Requirement already satisfied: nvidia-curand-cu12==10.3.7.77 in /usr/local/lib/python3.12/dist-packages (from torch) (10.3.7.77)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.1.2 in /usr/local/lib/python3.12/dist-packages (from torch) (11.7.1.2)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.4.2 in /usr/local/lib/python3.12/dist-packages (from torch) (12.5.4.2)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.3 in /usr/local/lib/python3.12/dist-packages (from torch) (2.27.3)
Requirement already satisfied: nvidia-nvtx-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch) (12.6.77)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.6.85 in /usr/local/lib/python3.12/dist-packages (from torch) (12.6.85)
Requirement already satisfied: nvidia-cufile-cu12==1.11.1.6 in /usr/local/lib/python3.12/dist-packages (from torch) (1.11.1.6)
Requirement already satisfied: triton==3.4.0 in /usr/local/lib/python3.12/dist-packages (from torch) (3.4.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (from wordcloud) (11.3.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.4.9)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: pandas>=1.2 in /usr/local/lib/python3.12/dist-packages (from seaborn) (2.2.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (1.2.0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart_open>=1.8.1->gensim) (2.0.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch) (3.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (2025.10.5)
<frozen runpy>:128: RuntimeWarning: 'nltk.downloader' found in sys.modules after import of package 'nltk', but prior to execution of 'nltk.downloader'; this may result in unpredictable behaviour
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [2]:
import pandas as pd
import numpy as np
import json
import matplotlib.pyplot as plt
import seaborn as sns

import nltk
nltk.download('punkt')
nltk.download('stopwords')

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

In [5]:
file_path = "/content/data.raw.json"

with open(file_path, "r") as f:
    data = json.load(f)

df = pd.DataFrame(data)
df.head()

,id,title,abstract,keywords,authors,venue,date,teams
0,5096000,Diffusion-based spectral super-resolution of t...,Third octave spectral recording of acoustic se...,"[speech privacy, generative audio, acoustic se...","[Modan Tailleur, Chaymae Benaatia, Mathieu Lag...",[info.info-ai],2025-09-08T00:00:00Z,"[AAU, LS2N]"
1,5113219,Ambiances. A Sensitivity to Ordinary Situations,"How do ambiances shape our sensory, social, an...","[ambiance, atmosphere, ambiances, atmospheres,...","[Jean-Paul Thibaud, Nicolas Tixier, David Zerbib]","[shs.archi, sde.es, shs, shs.art]",2025-09-08T00:00:00Z,[AAU]
2,5129109,Sensory Urban Mobilities: Experiences and Uses...,Beyond documenting all the sensory effects of ...,"[mobilité urbaine, perception sensible, transp...",[Damien Masson],[shs.archi],2025-07-01T00:00:00Z,[AAU]
3,5129157,Preprint_Extended / disabled bodies &amp; atmo...,As much as a symbolic construction or an objec...,"[ambiances, criticism, disabled bodies, forms ...",[Rachel Thomas],[shs],2025-05-11T00:00:00Z,[AAU]
4,5116799,Comparison of GNSS LOS/NLOS Labeling Technique...,The distinction between Line-of-Sight (LOS) an...,"[gnss, satellite visibility, losnlos, sky view...","[Benjamin Beaucamp, Thomas Leduc, Myriam Servi...",[info.info-ts],2025-04-28T00:00:00Z,[AAU]

In [12]:
stop_words = set(stopwords.words('english'))

def clean_text(text):
    if pd.isna(text):
        return ""
    tokens = word_tokenize(text.lower())
    tokens = [t for t in tokens if t.isalnum() and t not in stop_words]
    return " ".join(tokens)

df["clean_title"] = df["title"].apply(clean_text)
df["clean_abstract"] = df["abstract"].apply(clean_text)
df.head()

,id,title,abstract,keywords,authors,venue,date,teams,clean_title,clean_abstract,text
0,5096000,Diffusion-based spectral super-resolution of t...,Third octave spectral recording of acoustic se...,"[speech privacy, generative audio, acoustic se...","[Modan Tailleur, Chaymae Benaatia, Mathieu Lag...",[info.info-ai],2025-09-08T00:00:00Z,"[AAU, LS2N]",spectral third octave acoustic sensor data pri...,third octave spectral recording acoustic senso...,diffusionbased spectral superresolution third ...
1,5113219,Ambiances. A Sensitivity to Ordinary Situations,"How do ambiances shape our sensory, social, an...","[ambiance, atmosphere, ambiances, atmospheres,...","[Jean-Paul Thibaud, Nicolas Tixier, David Zerbib]","[shs.archi, sde.es, shs, shs.art]",2025-09-08T00:00:00Z,[AAU],ambiances sensitivity ordinary situations,ambiances shape sensory social built environme...,ambiances sensitivity ordinary situations ambi...
2,5129109,Sensory Urban Mobilities: Experiences and Uses...,Beyond documenting all the sensory effects of ...,"[mobilité urbaine, perception sensible, transp...",[Damien Masson],[shs.archi],2025-07-01T00:00:00Z,[AAU],sensory urban mobilities experiences uses ambi...,beyond documenting sensory effects transportat...,sensory urban mobilities experiences uses ambi...
3,5129157,Preprint_Extended / disabled bodies &amp; atmo...,As much as a symbolic construction or an objec...,"[ambiances, criticism, disabled bodies, forms ...",[Rachel Thomas],[shs],2025-05-11T00:00:00Z,[AAU],disabled bodies amp atmospheres,much symbolic construction object social repre...,preprintextended disabled bodies amp atmospher...
4,5116799,Comparison of GNSS LOS/NLOS Labeling Technique...,The distinction between Line-of-Sight (LOS) an...,"[gnss, satellite visibility, losnlos, sky view...","[Benjamin Beaucamp, Thomas Leduc, Myriam Servi...",[info.info-ts],2025-04-28T00:00:00Z,[AAU],comparison gnss labeling techniques based 3d m...,distinction los nlos signals crucial improving...,comparison gnss losnlos labeling techniques ba...

In [13]:
import nltk
import re
from nltk.corpus import stopwords
nltk.download('stopwords')

stop_words = set(stopwords.words("english"))

def clean_text(text):
    if not isinstance(text, str):
        return ""
    text = text.lower()
    text = re.sub(r'[^a-zA-Z\s]', '', text)
    tokens = text.split()
    tokens = [t for t in tokens if t not in stop_words]
    return " ".join(tokens)

df["clean_title"] = df["title"].apply(clean_text)
df["clean_abstract"] = df["abstract"].apply(clean_text)
df["text"] = df["clean_title"] + " " + df["clean_abstract"]

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [14]:
df["venue"] = df["venue"].apply(lambda x: x[0] if isinstance(x, list) and len(x)>0 else "unknown")
from sklearn.preprocessing import LabelEncoder

lbl = LabelEncoder()
df["label"] = lbl.fit_transform(df["venue"])
df["label"].value_counts().head()

label
270    2427
0       883
97      862
289     839
304     817
Name: count, dtype: int64

In [17]:
from sklearn.model_selection import train_test_split

X = df["text"]
y = df["label"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

ValueError: The least populated class in y has only 1 member, which is too few. The minimum number of groups for any class cannot be less than 2.